### ISSUE TITLE
Expose a health check endpoint?

### ISSUE THREAD

**Issue by duanshiqiang** [discourse/prometheus_exporter#69] opened 2019-04-17 04:42 UTC
Currently we are facing issues that the collector process stops working after running for some time (few days) and the /metrics response having "ruby_collector_working 0".

All of our workloads are running in kubernetes and we are running the collector process in a sidecar container. So if the collector web server (WEBrick process) can have a health check endpoint like '/healthz' then we can use it as the container livenessProbe so kubernetes can help us restart the container when the collector stops working.

**Comment by SamSaffron** [comment] 2019-04-17 05:32
This is a bit odd, we have not seen collectors die across our infrastructure at all. 

This metric is there to inform the central server that the collector has no metrics. My guess is that this would happen if you restarted the collector container and somehow your old containers were no longer able to talk to it. 

I think the remediation here is actually to restart the entire pod. 

Quick question first, do you have IPv6 stability across container destroy/create? Are you communicating via v4? If so do you have port stability?

**Comment by duanshiqiang** [comment] 2019-04-17 06:16
Hi @SamSaffron Thanks for your reply. We are using ipv4 only in our infrastructure.

We have subclassed `PrometheusExporter::Server::WebCollector` and running the collector with command like this:

`bundle exec prometheus_exporter -a lib/prometheus/web_with_tenant_collector.rb`

What we are observing is that the memory usage of the prometheus_exporter can go up even to over 1 GB which is really strange.

Also what you are implying in your reply is that you are running the prometheus_exporter as a central server? We are running it as a sidecar of each puma server (we are having over 90 pods) which I guess is not recommended. And I do find that since some metrics are of type `summary`, especially those percentiles metrcs, we are not able to write promql to recalculate it among all the server instances which is quite sad.

One thing we are afraid of running the prometheus_expoter as a central server is that there's a single point of failure and we found if the prometheus_expoter is down, our puma server will be flooded by error logs like:

`Prometheus Exporter, failed to send message Cannot assign requested address - connect(2) for "localhost" port 9394`

**Comment by SamSaffron** [comment] 2019-04-17 06:23
1GB in a collector is a big concern that would mean some list is ever growing, summary metrics do have a roof on them, but I guess if you keep adding metrics problems can arise. 

Can you look at one of your collectors say at 512MB and see how many metrics you have reported? then maybe do a ruby heap dump via rbtrace to see where the leak is. 

You can run as many collectors as you need but certainly there is a memory impact, that said it should be small in the big scheme. 

This is one of our collectors on a very busy server that has been running since March 27 (RSS is merely 36872)

```
discour+   109  0.7  0.0 317384 36872 ?        Sl   Mar26 233:13 ruby /var/www/discourse/plugins/discourse-prometheus/bin/collector 9405 79
```

Let's first work out what your memory issue is prior to attempting workarounds here.

**Comment by Fivell** [comment] 2019-06-13 12:12
@duanshiqiang  we also noticed memory leak in exporter, do u have any updates ?

**Comment by Fivell** [comment] 2019-06-27 09:30
@SamSaffron 
>> This is one of our collectors on a very busy server that has been running since March 27 (RSS is merely 36872)

are you using last version or maybe some previous one ?

**Comment by SamSaffron** [comment] 2019-06-27 10:48
Whatever this is I need more data, can you run through the steps here

https://samsaffron.com/archive/2015/03/31/debugging-memory-leaks-in-ruby

**Comment by Fivell** [comment] 2019-07-01 12:13
@SamSaffron  thanks for your article, I started exporter and launched ab script for both  metrics endpoint and some rails app endpoint .
After rss became bigger 
```
ps x -o rss,vsz,command | grep prometheus_exporter
 71504  4380208 ruby bin/prometheus_exporter
```

I started to repeat everything from your guide.
I have dump now and can see generations.
```
generation  objects 61981
generation 28 objects 2227
generation 29 objects 3697
generation 30 objects 1044
generation 31 objects 2761
generation 32 objects 2
generation 190 objects 22
generation 428 objects 44
generation 429 objects 22
generation 430 objects 22
generation 431 objects 44
generation 432 objects 22
generation 434 objects 26
generation 435 objects 44
generation 436 objects 22
generation 437 objects 22
generation 438 objects 44
generation 439 objects 22
generation 440 objects 22
generation 441 objects 88
generation 442 objects 374
generation 443 objects 264
generation 515 objects 22
generation 779 objects 22
generation 1041 objects 22
generation 1250 objects 22
generation 1508 objects 22
generation 1751 objects 22
generation 1808 objects 22
generation 1940 objects 22
generation 2186 objects 22
generation 2415 objects 22
generation 2527 objects 22
generation 2528 objects 22
generation 2529 objects 22
generation 2530 objects 44
generation 2531 objects 22
generation 2532 objects 22
generation 2533 objects 22
generation 2534 objects 22
generation 2664 objects 22
generation 2914 objects 22
generation 3171 objects 22
generation 3312 objects 1
generation 3315 objects 395
generation 3316 objects 6
```


So i picked up 3315 generation for detailed analyzing.
```
/Users/*****************/.rvm/gems/ruby-2.5.5@api3/bundler/gems/prometheus_exporter-0df4dcd79d65/lib/prometheus_exporter.rb:15 * 110
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:532 * 33
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:151 * 24
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:286 * 21
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:204 * 12
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:149 * 12
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:222 * 12
/Users/*****************/.rvm/gems/ruby-2.5.5@api3/bundler/gems/prometheus_exporter-0df4dcd79d65/bin/prometheus_exporter:86 * 10
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:196 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:478 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpservlet/abstract.rb:103 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:195 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:290 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:170 * 7
eval:1 * 7
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:144 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:187 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:255 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:260 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:186 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:33 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/generic.rb:335 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:76 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:44 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:41 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:542 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpresponse.rb:102 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:431 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:430 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:429 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:428 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:426 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:236 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:233 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:176 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:173 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:168 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:166 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:72 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpresponse.rb:108 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpresponse.rb:106 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:71 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/socket.rb:1313 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:290 * 3
/Users/*****************/.rvm/gems/ruby-2.5.5@api3/bundler/gems/prometheus_exporter-0df4dcd79d65/lib/prometheus_exporter/metric/counter.rb:23 * 3
/Users/*****************/.rvm/gems/ruby-2.5.5@api3/bundler/gems/prometheus_exporter-0df4dcd79d65/lib/prometheus_exporter.rb:15 * 110
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:532 * 33
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:151 * 24
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:286 * 21
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:204 * 12
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:149 * 12
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:222 * 12
/Users/*****************/.rvm/gems/ruby-2.5.5@api3/bundler/gems/prometheus_exporter-0df4dcd79d65/bin/prometheus_exporter:86 * 10
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:196 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:478 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpservlet/abstract.rb:103 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:195 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:290 * 9
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:170 * 7
eval:1 * 7
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:144 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:187 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:255 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:260 * 6
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:186 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httputils.rb:33 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/generic.rb:335 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:76 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:44 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:41 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:542 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpresponse.rb:102 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:431 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:430 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:429 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:428 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:426 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:236 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/utils.rb:233 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:176 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:173 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:168 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:166 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:72 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpresponse.rb:108 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpresponse.rb:106 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:71 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/socket.rb:1313 * 3
/Users/*****************/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httprequest.rb:290 * 3
/Users/*****************/.rvm/gems/ruby-2.5.5@api3/bundler/gems/prometheus_exporter-0df4dcd79d65/lib/prometheus_exporter/metric/counter.rb:23 * 3
```

```lib/prometheus_exporter.rb:15 * 110 ``` points to   ``` Oj.compat_load(obj)```



Can you please suggest what next to do ?

**Comment by SamSaffron** [comment] 2019-07-02 00:04
3315 is not a good one to pic ... 

generation 1250 objects 22
generation 1508 objects 22

This looks like a steady object leak of sorts, what are the objects? 

Note rss there is 71504 which is not enormous but could be better.

**Comment by Fivell** [comment] 2019-07-02 07:01
@SamSaffron , they all are pointed to ```prometheus_exporter-0df4dcd79d65/lib/prometheus_exporter.rb:15 * 22```

**Comment by SamSaffron** [comment] 2019-07-02 07:26
That is an indicator that you are collecting a giant pile of metric.

What metrics do you have, do you have a script that can repro the issue?

**Comment by Fivell** [comment] 2019-07-02 07:35
@SamSaffron  https://gist.github.com/Fivell/224a9cda0fadf1ff323a730c5a0d36dc , as I told i just call several endpoints thousands times using `ab`

**Comment by Fivell** [comment] 2019-07-02 14:22
@SamSaffron  I also repeated that on staging env
after 1 day logs are full of 
```
Jul 02 13:08:11 billing-prometheus-exrpoter-debug bundle[1579]: Generating Prometheus metrics text timed out
```
was created as separate issue(#77)

metrics output 
```
# HELP ruby_collector_working Is the master process collector able to collect metrics
# TYPE ruby_collector_working gauge
ruby_collector_working 0


# HELP ruby_collector_rss total memory used by collector process
# TYPE ruby_collector_rss gauge
ruby_collector_rss 571297792


# HELP ruby_collector_metrics_total Total metrics processed by exporter web.
# TYPE ruby_collector_metrics_total counter
ruby_collector_metrics_total 85085


# HELP ruby_collector_sessions_total Total send_metric sessions processed by exporter web.
# TYPE ruby_collector_sessions_total counter
ruby_collector_sessions_total 13350


# HELP ruby_collector_bad_metrics_total Total mis-handled metrics by collector.
# TYPE ruby_collector_bad_metrics_total counter
ruby_collector_bad_metrics_total 0


```
and heap data analyzing is also pointed to

```
/root/prometheus_exporter/lib/prometheus_exporter.rb:15 * 1339
```

**Comment by Fivell** [comment] 2019-07-02 17:51
after trying json instead of oj have same results but ```/usr/lib/ruby/2.5.0/json/common.rb:156 * 1040```

**Comment by SamSaffron** [comment] 2019-07-03 07:00
Fundamentally all the data is entering from a single entry point: 

https://github.com/discourse/prometheus_exporter/blob/master/lib/prometheus_exporter/server/collector.rb#L26-L28

So what you can do here to create a 100% reproduction of the issue is log the "string" and "timestamp" to a file. 

Then if we have the file we can replay it ... mock time.now and Process.clock_gettime(Process::CLOCK_MONOTONIC) and reproduce the issue 100% consistently. 

Note that heapy dump is not showing anything terribly bad, yes there is bits of duplication but only 20mb or so are in Ruby heaps. 

Also I wonder maybe we are somehow getting VSZ on your server vs RSS?

**Comment by Fivell** [comment] 2019-07-03 16:01
@SamSaffron sample attached 
[prometheus-exrpoter-debug.log](https://github.com/discourse/prometheus_exporter/files/3355770/prometheus-exrpoter-debug.log)

![image](https://user-images.githubusercontent.com/120269/60606917-e4d7a780-9dc4-11e9-8085-2fcf2b8927ec.png)

**Comment by SamSaffron** [comment] 2019-07-04 01:08
That is not nearly enough data imo... Ruby boots at like 30mb and can get
to 60mb very easily with almost no load.

What we do at Discourse we run Ruby with a tighter memory footprint by
doing:

https://github.com/discourse/discourse-prometheus/blob/f5f791f0312c3a25fca67172c991505bdce44f13/lib/demon.rb#L18-L19

What I would like to see here is the graph of it reaching same 200M  with
the attached logs.

In the mean time it may be worth working on a standalone repro.

```
collector = PrometheusExporter::Server.Collector.new
process(log) do |str, time|
    mock_time(time)
    collector.process(str)
end
```

If we can get that then to repro a leak we can debug it very cleanly with
the memory profiler gem. Cause it basically will take seconds to reach the
same memory bloat you are seeing taking days.

**Comment by Fivell** [comment] 2019-07-04 08:55
@ SamSaffron I'm not sure time is somehow affects. 
FYI launched exporter locally with smaller frequency of PrometheusExporter::Instrumentation::Puma like this
```
after_worker_boot do
    require 'prometheus_exporter/instrumentation'
    PrometheusExporter::Instrumentation::Puma.start(frequency: 1)
  end
end
```
and have very soon this picture
```
 ps x -o rss,vsz,command | grep prometheus_exporter
196764  4646520 ruby /Users/****/.rvm/gems/ruby-2.5.5@api3/bin/prometheus_exporter  
```
[log.txt.zip](https://github.com/discourse/prometheus_exporter/files/3358507/log.txt.zip)

**Comment by Fivell** [comment] 2019-07-08 19:09
@SamSaffron  sample of this but without time mocking 
https://github.com/Fivell/exp_memory_test

shows after 25m file processing next
```
Total allocated: 267388634 bytes (2373642 objects)
Total retained:  83211730 bytes (864334 objects)

allocated memory by gem
-----------------------------------
 220305928  json
  47082706  other

allocated memory by file
-----------------------------------
 220305928  /Users/igorfedoronchuk/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/json/common.rb
  47082706  test.rb

allocated memory by location
-----------------------------------
 217064088  /Users/igorfedoronchuk/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/json/common.rb:156
  43770282  test.rb:12
   3312344  test.rb:11
   3241840  /Users/igorfedoronchuk/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/json/common.rb:155
        80  test.rb:13

allocated memory by class
-----------------------------------
 111253154  String
  94661728  JSON::Ext::Parser
  58161328  Hash
   3303920  Array
      8424  File
        80  Proc

allocated objects by gem
-----------------------------------
   1959164  json
    414478  other

allocated objects by file
-----------------------------------
   1959164  /Users/igorfedoronchuk/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/json/common.rb
    414478  test.rb

allocated objects by location
-----------------------------------
   1878118  /Users/igorfedoronchuk/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/json/common.rb:156
    331878  test.rb:12
     82599  test.rb:11
     81046  /Users/igorfedoronchuk/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/json/common.rb:155
         1  test.rb:13

allocated objects by class
-----------------------------------
   1964376  String
    245620  Hash
     82598  Array
     81046  JSON::Ext::Parser
         1  File
         1  Proc

retained memory by gem
-----------------------------------
  83211730  json
```
any suggestions?

**Comment by SamSaffron** [comment] 2019-07-08 20:00
Oh my ... this puma collector is a GIANT problem.

Compare to this:

https://github.com/discourse/prometheus_exporter/blob/32a6bd1f6c670096b4cc230b242a1f0cb8dcfb89/lib/prometheus_exporter/server/process_collector.rb#L64-L67


Can you see how it follows a clean pattern to clear up history.

Puma collector is doing none of this.

https://github.com/discourse/prometheus_exporter/blob/32a6bd1f6c670096b4cc230b242a1f0cb8dcfb89/lib/prometheus_exporter/server/puma_collector.rb#L49-L51

I accepted this as a community contribution as I am not a puma user in my
projects. But sadly this is a giant enormous issue.

https://github.com/discourse/prometheus_exporter/pull/34/files needs to be
redone to follow the same practice we do process collector.

The key here is instead of growing an array forever in the collector, this
needs to have some sort of max age defined so there is no situation where.

Can you try a PR to fix this, just copy the pattern used in process
collector for max age and see if you can figure out a clean way of deduping
(not critical cause this thing is 100% gauges), note how you will have to
start mocking time to see the fix actually working.

Thank you so much for persisting here! You went above and beyond.

I am sadly on holidays at the moment (for another 3 weeks) so I can not
really work on this but I will merge and push a gem once you test the fix.

**Comment by SamSaffron** [comment] 2019-07-08 20:08
@eviltrout I can not fix this... but it is a very big mess that impacts every consumer of this gem that uses Puma. (it does not impact Discourse, but is very not good) 

Can you get someone to fix this and push a new gem out there? I just gave you push on the gem. 

Fix is pretty straightforward, follow same pattern process collector uses so array does not grow forever.

**Comment by Fivell** [comment] 2019-07-09 09:47
@SamSaffron  started testing on staging with this https://github.com/didww/prometheus_exporter/commit/809b38259b91ccbf64eb2ef21e7aea3794f91ab6

**Comment by eviltrout** [comment] 2019-07-09 16:37
@SamSaffron I'll handle it, no worries.

**Comment by Fivell** [comment] 2019-07-09 17:06
@eviltrout 👍

**Comment by eviltrout** [comment] 2019-07-09 17:59
I reviewed @Fivell's PR and also noticed the unicorn collector has the same problem. It's been fixed in master and I'm releasing a new version right now.

**Closed by eviltrout** 2019-07-09 17:59 UTC

**Comment by Fivell** [comment] 2019-07-09 18:34
@eviltrout  thanks will finally test tomorrow, we have all of them, unicorns and pumas, one thing I can't figure out is that if discourse run on unicorn and unicorn collector has the same problem, how it can be that according to @SamSaffron 
>> This is one of our collectors on a very busy server that has been running since March 27 (RSS is merely 36872)

**Comment by eviltrout** [comment] 2019-07-09 18:41
@Fivell I reached out to operations when I found the unicorn problem because I had the same suspicion. It turns out the unicorn monitoring as part of this gem is not used by the discourse-prometheus plugin, so that one did not affect us either.

**Comment by Fivell** [comment] 2019-07-09 19:18
@eviltrout thanks for clarifications! Good luck
